### ISSUE TITLE
TypeError: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by reggi** [jgreene/watch-less#13]
```
thomas@workstation:shopify-react$ watch-less -e ".css"
updating: /Users/thomas/Desktop/shopify-react/holstee-components.css

/Users/thomas/.nvm/v0.10.32/lib/node_modules/watch-less/node_modules/less/lib/less/parser/parser.js:108
            imports.contents[fileInfo.filename] = str;
                   ^
TypeError: Cannot read property 'contents' of undefined
    at Object.Parser.parse (/Users/thomas/.nvm/v0.10.32/lib/node_modules/watch-less/node_modules/less/lib/less/parser/parser.js:108:20)
    at /Users/thomas/.nvm/v0.10.32/lib/node_modules/watch-less/cli.js:72:12
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by reggi** [comment]
I'm not trying to bash the work put into this project, just providing an alternative.

If you use a separate command that just watches files and the native less compiler itself by installing both:

```
npm i less onchange -g` 
```

Then you can use something like:

```
onchange "./stylesheets/*.less" -- lessc main.less > main.css
```

**Comment by jgreene** [comment]
Lack of upper bounds in package.json is what caused this.  I updated the project to use the less v2 api and added upper bounds so it shouldn't happen again.

That said, I don't use this project anymore so if anyone would like to take it over feel free.

**Comment by h3** [comment]
@reggi pretty neat :)

And if you want to see some output while writing the file:

```bash
onchange "./stylesheets/*.less" -- lessc main.less | tee main.css
```
